// packages/lit/src/components/ld-editor.ts
/**
 * LdEditor - Lit Web Component
 */

import { LitElement, html, css } from 'lit'
import { customElement, property, state, query } from 'lit/decorators.js'
import { Editor, type EditorOptions } from '@ldesign/editor-core'

/**
 * LDesign 编辑器 Web Component
 * 
 * @element ld-editor
 * 
 * @example
 * ```html
 * <ld-editor 
 *   content="<p>Hello World</p>" 
 *   placeholder="开始输入..."
 *   .on-change="${(e) => console.log(e.detail)}"
 * ></ld-editor>
 * ```
 * 
 * @fires change - 内容变化事件
 * @fires focus - 聚焦事件
 * @fires blur - 失焦事件
 */
@customElement('ld-editor')
export class LdEditor extends LitElement {
  static override styles = css`
    :host {
      display: block;
      width: 100%;
      height: 100%;
    }
    
    .editor-container {
      width: 100%;
      height: 100%;
    }
  `

  /**
   * 编辑器内容
   */
  @property({ type: String })
  content = ''

  /**
   * 占位符文本
   */
  @property({ type: String })
  placeholder = ''

  /**
   * 是否只读
   */
  @property({ type: Boolean })
  readonly = false

  /**
   * 是否自动聚焦
   */
  @property({ type: Boolean })
  autofocus = false

  /**
   * 是否启用虚拟滚动
   */
  @property({ type: Boolean, attribute: 'virtual-scroll' })
  virtualScroll = false

  /**
   * 是否启用WASM加速
   */
  @property({ type: Boolean, attribute: 'wasm' })
  wasm = false

  /**
   * AI提供商
   */
  @property({ type: String, attribute: 'ai-provider' })
  aiProvider = ''

  /**
   * 容器元素
   */
  @query('.editor-container')
  private containerElement?: HTMLDivElement

  /**
   * 编辑器实例
   */
  @state()
  private editor: Editor | null = null

  override connectedCallback(): void {
    super.connectedCallback()
  }

  override firstUpdated(): void {
    this.initializeEditor()
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback()
    this.destroyEditor()
  }

  /**
   * 初始化编辑器
   */
  private initializeEditor(): void {
    if (!this.containerElement) return

    const options: EditorOptions = {
      content: this.content,
      placeholder: this.placeholder,
      autofocus: this.autofocus,

      // 虚拟滚动
      virtualScroll: this.virtualScroll ? { enabled: true } : undefined,

      // WASM加速
      wasm: this.wasm ? { enabled: true } : undefined,

      // AI配置
      ai: this.aiProvider ? { provider: this.aiProvider as any } : undefined,

      // 事件处理
      onChange: (content: string) => {
        this.content = content
        this.dispatchEvent(new CustomEvent('change', {
          detail: content,
          bubbles: true,
          composed: true
        }))
      },

      onFocus: () => {
        this.dispatchEvent(new Event('focus', {
          bubbles: true,
          composed: true
        }))
      },

      onBlur: () => {
        this.dispatchEvent(new Event('blur', {
          bubbles: true,
          composed: true
        }))
      }
    }

    this.editor = new Editor(options)
    this.editor.mount(this.containerElement)
  }

  /**
   * 销毁编辑器
   */
  private destroyEditor(): void {
    this.editor?.destroy?.()
    this.editor = null
  }

  /**
   * 监听属性变化
   */
  override updated(changedProperties: Map<string, any>): void {
    // 内容变化
    if (changedProperties.has('content') && this.editor) {
      const currentContent = this.editor.getContent?.()
      if (this.content !== currentContent) {
        this.editor.setContent?.(this.content)
      }
    }

    // 只读状态变化
    if (changedProperties.has('readonly') && this.editor) {
      this.editor.setEditable?.(!this.readonly)
    }
  }

  /**
   * 获取内容
   */
  getContent(): string {
    return this.editor?.getContent?.() || this.content
  }

  /**
   * 设置内容
   */
  setContent(content: string): void {
    this.content = content
    this.editor?.setContent?.(content)
  }

  /**
   * 聚焦编辑器
   */
  focus(): void {
    this.editor?.focus?.()
  }

  override render() {
    return html`
      <div class="editor-container"></div>
    `
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ld-editor': LdEditor
  }
}

// packages/vue/src/components/LdEditor.tsx
/**
 * LdEditor - Vue 3 编辑器组件
 */

import { defineComponent, onMounted, onUnmounted, ref, watch, type PropType } from 'vue'
import type { EditorOptions } from '@ldesign/editor-core'
import { Editor } from '@ldesign/editor-core'

export interface EditorProps extends Omit<EditorOptions, 'onChange' | 'onUpdate'> {
  /** v-model绑定的内容 */
  modelValue?: string
}

export interface EditorEmits {
  /** 内容更新事件 */
  'update:modelValue': [value: string]
  /** 变化事件 */
  'change': [content: string]
  /** 聚焦事件 */
  'focus': []
  /** 失焦事件 */
  'blur': []
}

export interface EditorInstance {
  /** 编辑器实例 */
  editor: Editor | null
  /** 获取内容 */
  getContent: () => string
  /** 设置内容 */
  setContent: (content: string) => void
  /** 聚焦 */
  focus: () => void
}

/**
 * LDesign 编辑器 Vue 组件
 * 
 * @example
 * ```vue
 * <template>
 *   <LdEditor v-model="content" placeholder="开始输入..." />
 * </template>
 * 
 * <script setup lang="ts">
 * import { ref } from 'vue'
 * import { LdEditor } from '@ldesign/editor-vue'
 * 
 * const content = ref('<p>Hello World</p>')
 * </script>
 * ```
 */
export const LdEditor = defineComponent({
  name: 'LdEditor',

  props: {
    /**
     * 编辑器内容（v-model）
     */
    modelValue: {
      type: String,
      default: ''
    },

    /**
     * 占位符文本
     */
    placeholder: {
      type: String,
      default: ''
    },

    /**
     * 是否只读
     */
    readonly: {
      type: Boolean,
      default: false
    },

    /**
     * 是否自动聚焦
     */
    autofocus: {
      type: Boolean,
      default: false
    },

    /**
     * 虚拟滚动配置
     */
    virtualScroll: {
      type: Object as PropType<EditorOptions['virtualScroll']>,
      default: undefined
    },

    /**
     * WASM加速配置
     */
    wasm: {
      type: Object as PropType<EditorOptions['wasm']>,
      default: undefined
    },

    /**
     * AI配置
     */
    ai: {
      type: Object as PropType<EditorOptions['ai']>,
      default: undefined
    },

    /**
     * PWA配置
     */
    pwa: {
      type: Object as PropType<EditorOptions['pwa']>,
      default: undefined
    },

    /**
     * 调试面板配置
     */
    debugPanel: {
      type: Object as PropType<EditorOptions['debugPanel']>,
      default: undefined
    },

    /**
     * 插件列表
     */
    plugins: {
      type: Array as PropType<EditorOptions['plugins']>,
      default: () => []
    }
  },

  emits: {
    /**
     * v-model更新事件
     */
    'update:modelValue': (value: string) => true,

    /**
     * 内容变化事件
     */
    'change': (content: string) => true,

    /**
     * 聚焦事件
     */
    'focus': () => true,

    /**
     * 失焦事件
     */
    'blur': () => true
  },

  setup(props, { emit, expose }) {
    const containerRef = ref<HTMLDivElement>()
    let editor: Editor | null = null

    onMounted(() => {
      if (!containerRef.value) return

      // 创建编辑器实例
      editor = new Editor({
        content: props.modelValue,
        placeholder: props.placeholder,
        autofocus: props.autofocus,
        virtualScroll: props.virtualScroll,
        wasm: props.wasm,
        ai: props.ai,
        pwa: props.pwa,
        debugPanel: props.debugPanel,
        plugins: props.plugins,

        // 事件处理
        onChange: (content: string) => {
          emit('update:modelValue', content)
          emit('change', content)
        },

        onFocus: () => {
          emit('focus')
        },

        onBlur: () => {
          emit('blur')
        }
      })

      // 挂载编辑器
      editor.mount(containerRef.value)
    })

    // 监听 modelValue 变化
    watch(() => props.modelValue, (newValue) => {
      if (editor && newValue !== editor.getContent?.()) {
        editor.setContent?.(newValue)
      }
    })

    // 监听只读状态
    watch(() => props.readonly, (readonly) => {
      if (editor) {
        editor.setEditable?.(!readonly)
      }
    })

    onUnmounted(() => {
      editor?.destroy?.()
      editor = null
    })

    // 暴露方法给父组件
    const instance: EditorInstance = {
      editor,
      getContent: () => editor?.getContent?.() || '',
      setContent: (content: string) => editor?.setContent?.(content),
      focus: () => editor?.focus?.()
    }

    expose(instance)

    return () => (
      <div
        ref={containerRef}
        class="ld-editor-vue-wrapper"
        style={{
          width: '100%',
          height: '100%'
        }}
      />
    )
  }
})

export default LdEditor
