// packages/solid/src/components/Editor.tsx
import type { Component, JSX } from 'solid-js'
import { onMount, onCleanup, createEffect } from 'solid-js'
import { Editor as CoreEditor } from '@ldesign/editor-core'
import type { EditorOptions } from '@ldesign/editor-core'

export interface EditorProps extends Partial<EditorOptions> {
  content?: string
  onUpdate?: (html: string) => void
  class?: string
  style?: JSX.CSSProperties
}

export const Editor: Component<EditorProps> = (props) => {
  let editorRef: HTMLDivElement
  let editorInstance: CoreEditor | null = null

  onMount(() => {
    editorInstance = new CoreEditor({
      element: editorRef,
      content: props.content || '',
      editable: props.editable,
      plugins: props.plugins,
    })

    if (props.onUpdate) {
      editorInstance.on('update', () => {
        const html = editorInstance!.getContent()
        props.onUpdate?.(html)
      })
    }
  })

  createEffect(() => {
    if (editorInstance && props.content !== undefined) {
      const currentContent = editorInstance.getContent()
      if (currentContent !== props.content) {
        editorInstance.setContent(props.content)
      }
    }
  })

  onCleanup(() => {
    editorInstance?.destroy()
  })

  return (
    <div
      ref={editorRef!}
      class={props.class}
      style={props.style}
    />
  )
}

// packages/preact/src/components/Editor.tsx
import { h } from 'preact'
import { useEffect, useRef } from 'preact/hooks'
import { Editor as CoreEditor } from '@ldesign/editor-core'
import type { EditorOptions } from '@ldesign/editor-core'

export interface EditorProps extends Partial<EditorOptions> {
  content?: string
  onChange?: (html: string) => void
  className?: string
  style?: h.JSX.CSSProperties
}

export function Editor(props: EditorProps) {
  const { content, onChange, className, style, ...editorOptions } = props
  const editorRef = useRef<HTMLDivElement>(null)
  const instanceRef = useRef<CoreEditor | null>(null)

  useEffect(() => {
    if (!editorRef.current)
      return

    instanceRef.current = new CoreEditor({
      element: editorRef.current,
      content: content || '',
      ...editorOptions,
    })

    if (onChange) {
      instanceRef.current.on('update', () => {
        const html = instanceRef.current!.getContent()
        onChange(html)
      })
    }

    return () => {
      instanceRef.current?.destroy()
    }
  }, [])

  useEffect(() => {
    if (instanceRef.current && content !== undefined) {
      const currentContent = instanceRef.current.getContent()
      if (currentContent !== content) {
        instanceRef.current.setContent(content)
      }
    }
  }, [content])

  return (
    <div
      ref={editorRef}
      className={className}
      style={style}
    />
  )
}
